# Generated by Django 5.0.6 on 2024-07-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signing',
            name='season',
            field=models.IntegerField(),
        ),
    ]
