# Generated by Django 5.0.6 on 2024-05-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='Club',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='equipos',
            old_name='PreviousTeam',
            new_name='previous_team',
        ),
        migrations.RenameField(
            model_name='fichaje',
            old_name='Signing',
            new_name='signing',
        ),
        migrations.RenameField(
            model_name='temporada',
            old_name='Season',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='valor',
            old_name='MarketValue',
            new_name='market_value',
        ),
    ]
