# Generated by Django 5.0.6 on 2024-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_fichaje_signing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='height',
            field=models.FloatField(),
        ),
    ]
